debug: fix operating system dependencies

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -14,6 +14,11 @@ env:
   KEYCLOAK_CLIENT_SECRET: ${{ secrets.KEYCLOAK_CLIENT_SECRET }}
   NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
 
+# Cancel current job when pushing new commit into the PR
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
+
 jobs:
   install-dev-tools:
     runs-on: ubuntu-latest
@@ -207,21 +212,18 @@ jobs:
       - backend-docker-build
       - frontend-docker-build
       - install-dev-tools
-    runs-on: ubuntu-latest
     timeout-minutes: 60
+    runs-on: ${{ matrix.os }}
     strategy:
-      fail-fast: false
+      fail-fast: false # keep running other jobs if one fails
       matrix:
-        include:
-          - project: chromium
-            os: ubuntu-latest
-            cache_dir: ~/.cache/ms-playwright
-          - project: firefox
-            os: ubuntu-latest
-            cache_dir: ~/.cache/ms-playwright
-          - project: webkit
-            os: macos-12
-            cache_dir: ~/Library/Caches/ms-playwright
+        os: [macos-latest, windows-latest, ubuntu-latest]
+        browser: [chromium, firefox, webkit]
+    env:
+      # Playwright uses different paths on different OS's.
+      # To make it work cross-platform, we need to set the path manually.
+      # Alternatively, `PLAYWRIGHT_BROWSERS_PATH=0` install binaries in node_modules
+      PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/ms-playwright
     steps:
       - uses: actions/checkout@v3
 
@@ -236,16 +238,43 @@ jobs:
           keycloak_client_secret: ${{ env.KEYCLOAK_CLIENT_SECRET }}
           nextauth_secret: ${{ env.NEXTAUTH_SECRET }}
 
-      - name: ⚡️ cache Playwright binaries
+      # Install dependencies with cache
+      - name: ⚡️ cache dependencies
+        id: cache-deps
         uses: actions/cache@v3
-        id: playwright-cache
         with:
-          path: ${{ matrix.cache_dir }}
-          key: ${{ runner.os }}-${{ matrix.project }}-playwright
+          path: ~/.cache/yarn
+          key: modules-${{ hashFiles('yarn.lock') }}
 
-      - name: 📥 install Playwright ${{ matrix.project }}
-        if: steps.playwright-cache.outputs.cache-hit != 'true'
-        run: yarn playwright install --with-deps ${{ matrix.project }}
+      - name: 📥 install dependencies
+        if: steps.cache-deps.outputs.cache-hit != 'true'
+        run: yarn install --frozen-lockfile --ignore-scripts
+
+      # Install Playwright browsers with cache
+      - name: ⚡️ cache Playwright version
+        shell: bash
+        run: echo "PLAYWRIGHT_VERSION=$(node -p 'require("@playwright/test/package.json").version')" >> $GITHUB_ENV
+        id: playwright-version
+
+      - name: ⚡️ cache Playwright browsers and maybe dependencies
+        id: cache-browsers
+        uses: actions/cache@v3
+        with:
+          key: ${{ runner.os }}-${{ matrix.browser }}-playwright-${{ steps.playwright-version.outputs.PLAYWRIGHT_VERSION }}
+          path: ${{ env.PLAYWRIGHT_BROWSERS_PATH }}
+
+      - name: Install Playwright browsers
+        if: steps.cache-browsers.outputs.cache-hit != 'true'
+        run: yarn playwright install ${{ matrix.browser }}
+      - name: 📥 install Playwright dependencies
+        # Linux and Windows cannot cache deps.
+        # See: https://github.com/microsoft/playwright/issues/22146#issuecomment-1495821016
+        # if: steps.cache-browsers.outputs.cache-hit != 'true' || runner.os != 'macOS'
+        # BUT except for linux-webkit, they already include most of the necessary dependencies.
+        # So unless you use things like graphics, fonts, video playback etc. and you run into a problem,
+        # You can speed up your CI by using this less strict condition:
+        if: steps.cache-browsers.outputs.cache-hit != 'true' || (runner.os == 'Linux' && matrix.browser == 'webkit')
+        run: yarn playwright install-deps ${{ matrix.browser }}
         working-directory: ./client
 
       - name: 🎭 run Playwright
