fix: happo Add a new operator\default

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -255,6 +255,8 @@ jobs:
       - name: 🎭 run Playwright
         run: |
           npx happo-e2e -- npx playwright test --project=${{ matrix.project }} client/e2e/*
+          if [ $? -ne 0 ]; then
+            echo "::set-output name=result::failure"
         env:
           XDEBUG: pw:api,pw:browser*
           API_URL: http://127.0.0.1:8000/api/
@@ -299,7 +301,7 @@ jobs:
     name: 📊 e2e report artifact
     runs-on: ubuntu-latest
     needs: [e2e-tests]
-    if: ${{ always() }}
+    if: ${{ needs.e2e-tests.result == 'failure' }}
     steps:
       - name: Download blob reports from GitHub Actions Artifacts
         uses: actions/download-artifact@v4
