chore: test

diff --git a/.github/workflows/zap-owasp.yaml b/.github/workflows/zap-owasp.yaml
--- a/.github/workflows/zap-owasp.yaml
+++ b/.github/workflows/zap-owasp.yaml
@@ -14,30 +14,34 @@ jobs:
       - uses: actions/checkout@v4
       - name: dev env setup
         uses: ./.github/actions/dev-env-setup
-      - name: run app locally
-        uses: ./.github/actions/run-registration1-app
-        with:
-          django_secret_key: ${{ env.DJANGO_SECRET_KEY }}
-      - name: ZAP Frontend Scan
-        uses: zaproxy/action-baseline@v0.12.0
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          docker_name: "ghcr.io/zaproxy/zaproxy:stable"
-          target: "http://localhost:3000/"
-          rules_file_name: ".zap/rules-frontend.tsv"
-          cmd_options: "-a -d -T 5 -m 2"
-          issue_title: OWASP Baseline - Frontend
-          fail_action: false
-      - name: ZAP Backend Scan
-        uses: zaproxy/action-baseline@v0.12.0
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          docker_name: "ghcr.io/zaproxy/zaproxy:stable"
-          target: "http://0.0.0.0:8000/"
-          rules_file_name: ".zap/rules-backend.tsv"
-          cmd_options: "-a -d -T 5 -m 2"
-          issue_title: OWASP Baseline - Backend
-          fail_action: false
+      # - name: run app locally
+      #   uses: ./.github/actions/run-registration1-app
+      #   with:
+      #     django_secret_key: ${{ env.DJANGO_SECRET_KEY }}
+      # - name: ZAP Frontend Scan
+      #   uses: zaproxy/action-baseline@v0.12.0
+      #   with:
+      #     token: ${{ secrets.GITHUB_TOKEN }}
+      #     docker_name: "ghcr.io/zaproxy/zaproxy:stable"
+      #     target: "http://localhost:3000/"
+      #     rules_file_name: ".zap/rules-frontend.tsv"
+      #     cmd_options: "-a -d -T 5 -m 2"
+      #     issue_title: OWASP Baseline - Frontend
+      #     fail_action: false
+      # - name: ZAP Backend Scan
+      #   uses: zaproxy/action-baseline@v0.12.0
+      #   with:
+      #     token: ${{ secrets.GITHUB_TOKEN }}
+      #     docker_name: "ghcr.io/zaproxy/zaproxy:stable"
+      #     target: "http://0.0.0.0:8000/"
+      #     rules_file_name: ".zap/rules-backend.tsv"
+      #     cmd_options: "-a -d -T 5 -m 2"
+      #     issue_title: OWASP Baseline - Backend
+      #     fail_action: false
+      - name: Try to fail
+        run: exit 1
+      - name: Print message if we don't fail
+        run: echo Should not get here
   retry-on-failure:
     if: failure() && fromJSON(github.run_attempt) < 3
     needs: [zap-scan]
@@ -46,4 +50,4 @@ jobs:
       - env:
           GH_REPO: ${{ github.repository }}
           GH_TOKEN: ${{ github.token }}
-        run: gh workflow run retry-workflow.yml -F run_id=${{ github.run_id }}
+        run: gh workflow run retry-workflow.yaml -F run_id=${{ github.run_id }}
